spring.application.name=buscaativa
spring.profiles.active=dev
spring.jpa.open-in-view=true
logging.level.org.springframework.security=TRACE
agenda.horarios.manha.inicio=07:00
agenda.horarios.manha.fim=11:30
agenda.horarios.tarde.inicio=13:00
agenda.horarios.tarde.fim=18:30
agenda.intervalo-minutos=30
