spring.application.name=buscaativa
spring.profiles.active=dev
spring.jpa.open-in-view=true
logging.level.org.springframework.security=TRACE

api.security.token.secret=u$B5v9xK2zR8qP4nM1fL6jQ0wE7yT3vH9sA8dG5jF2kL4pQ9oR1tY6uI3oP7nW0mX